create database school;
use school;
show databases;
create table student(id int primary key auto_increment,name varchar(20),department varchar(30));
desc student;
insert into student values(1,'Akshara','mca');
insert into student values(2,'Aswathy','mca');
insert into student values(3,'Angha','mca');
insert into student values(4,'Megha','mca');
insert into student values(5,'swetha','mca');
insert into student values(6,'paru','mba');
commit;
select * from student;
insert into student values(7,'sneha','mca');
rollback;
insert into student values(8,'sneha','mca');
savepoint t1;
insert into student values(9,'varun','bca');
select * from student;
rollback to t1; 
