use mcetmca2021;
select name from customer where cust_id in (select cust_id from invoice_master where inv_date='2020-5-11');
select pname,price from product where prd_id in (select prd_id from invoice_item);
select pname from product where prd_id in(select prd_id from invoice_item where quantity >3);
select pname from product where prd_id not in(select prd_id from invoice_item);
select name from customer where cust_id in (select cust_id from invoice_master where inv_id in(select inv_id from invoice_item where prd_id in (select prd_id from product where pname ='powder')and (select prd_id from product where pname='pencil')));
select * from customer invoice_item where inv_id  in(select inv_id from invoice_master where cust_id in (select cust_id from customer where name='binu'));
select distinct name from customer where cust_id in (select cust_id from invoice_master where inv_id in(select inv_id from invoice_item where quantity >=2));
select pname ,quantity from product natural join invoice_item;
select * from invoice_master natural join invoice_item natural join product natural join customer where inv_date='2020-05-11';
select name,pname,inv_date from customer natural join product natural join invoice_master natural join invoice_item where pname='powder';
select * from customer left join invoice_master natural join invoice_item natural join product on customer .cust_id =invoice_master.cust_id;
create view customers as select name from customer natural join invoice_master;
select * from customers;
create view invoice_product as select pname,quantity,inv_id,prd_id as product_id from product natural join invoice_item; 
select * from invoice_product;
select cust_id as all_id from customer union select prd_id from product;
select prd_id,pname,price + 5 from product;
select pname from product where prd_id in(select prd_id from invoice_item where quantity=2);
