create database mcetmca2021;
use mcetmca2021;
show databases;
SHOW TABLES;
create table student1(student_ID varchar(6),student_name varchar(20));
insert into student1 values('mca1','Aswathy');
insert into student1 values('mca2','Lekshmi');
insert into student1 values('mca3','Akshara');
desc student1;
select * from student;
alter table student1 add loc varchar(20);
alter table student1 add dob date;
desc student1;
alter table student1 modify dob year;
select * from student1;
ALTER TABLE student1 DROP loc;
desc student1;
ALTER TABLE Student MODIFY Student_ID varchar(10);
create table customer1 (cust_id int primary key auto_increment , address varchar(30),city varchar(20),phn_no int);
desc customer;
create table product1 (prd_id int primary key auto_increment,pname varchar(20),price int default'0');
desc product;
create table invoice_master(inv_id int primary key auto_increment,cust_id int,constraint cust_id foreign key(cust_id)REFERENCES customer(cust_id),inv_date date);
desc invoice_master;
create table invoice_item(inv_id int,constraint inv_id foreign key(inv_id) references invoice_master(inv_id),prd_id int,constraint prd_id foreign key(prd_id) references product(prd_id),quantity int);
desc invoice_item;
select* from customer;
